<a href="https://colab.research.google.com/github/Bartosztakon/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array ([1.2, 2.1, 3.6], dtype= float)
A.dtype
print(A)

B = np.array([True, False])
A.dtype

[1.2 2.1 3.6]


dtype('float64')

In [ ]:
np.zeros(shape=(4, 10), dtype= 'float')

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.full(shape=(4, 10), fill_value=10.5, dtype= 'float')

array([[10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5]])

In [ ]:
np.arange(100,0, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [ ]:
np.linspace(start=0, stop=1, num=21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
import numpy as np
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A+B)
print(B-B)
print(A*B)
print(A/B)

[6 0 7 4]
[0 0 0 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]


In [ ]:
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.divide(A,B))

[6 0 7 4]
[0 2 1 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]


In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

In [ ]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [43]:
np.random.seed(1)
np.random.randn(10)
G = np.random.randn(10,4)

In [55]:
np.random.choice(['PYTHON', 'JAVA', 'SQL'])

'SQL'

In [54]:
data = np.arange(10)
np.random.shuffle(data)
data

array([4, 5, 3, 9, 1, 0, 6, 8, 2, 7])

In [59]:
np.exp(1)

2.718281828459045

In [65]:
np.all([2,3,1])

True

In [66]:
np.any([2,3,1])

True

In [74]:
bool(0)

True

In [86]:
A = np.random.rand(5)
A

array([0.02621099, 0.02830649, 0.24621107, 0.86002795, 0.53883106])

In [87]:
np.argmax(A)

3

In [88]:
np.argmin(A)

0

In [89]:
np.argsort(A)

array([0, 1, 2, 4, 3])

In [96]:
A = np.arange(20)
np.random.shuffle(A)
A

array([ 7,  6,  5, 17,  1, 12, 14, 11, 15,  9,  2,  4, 16, 19,  3, 13,  8,
       10, 18,  0])

In [97]:
A [2]

5

In [99]:
A[:2]

array([7, 6])

In [105]:
A = A.reshape(4,5)
A

array([[ 7,  6,  5, 17,  1],
       [12, 14, 11, 15,  9],
       [ 2,  4, 16, 19,  3],
       [13,  8, 10, 18,  0]])

In [111]:
A[1,3]

15

In [118]:
for row in A:
  print(row)

[ 7  6  5 17  1]
[12 14 11 15  9]
[ 2  4 16 19  3]
[13  8 10 18  0]


In [120]:
for item in A.flat:
  print(item)

7
6
5
17
1
12
14
11
15
9
2
4
16
19
3
13
8
10
18
0


In [124]:
A.reshape(5,4)

array([[ 7,  6,  5, 17],
       [ 1, 12, 14, 11],
       [15,  9,  2,  4],
       [16, 19,  3, 13],
       [ 8, 10, 18,  0]])

In [125]:
A.ravel()

array([ 7,  6,  5, 17,  1, 12, 14, 11, 15,  9,  2,  4, 16, 19,  3, 13,  8,
       10, 18,  0])

In [137]:
P = np.arange(start=-10, stop=10, step=0.5)
P = P.reshape(10, -1)
print(P)

[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]


In [141]:
P[np.bitwise_and(P > -5, P < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [142]:
P[np.bitwise_or(P > -5, P < 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])