<a href="https://colab.research.google.com/github/Bartosztakon/data-science-bootcamp/blob/main/G1_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [8]:
v1 = np.array([-1, 4])
v1

array([0, 4])

In [9]:
np.linalg.norm(v1)

4.0

In [10]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [12]:
p = np.array([3, 0, 1])
q = np.array([3, 4, 2])
np.linalg.norm(p - q)

4.123105625617661

In [15]:
X = np.array([[2, -1, 3],
             [3, 1, 0]])
Y = np.array([[2, 1, -1],
             [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)
print(np.dot(X,Y))

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]
[[13  9 -4]
 [ 6  2 -1]]


In [17]:
np.trace(Y)

1

In [23]:
C = np.eye(3, dtype=int)

In [29]:
A = np.linalg.inv(C)
print(C*A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
A = np.array([[2, 4], [1, -1]])
B = np.array([[10], [-1]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])